
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: check-merge-conflict
    -   id: detect-private-key
    -   id: detect-aws-credentials
    -   id: check-toml
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
        args: ['--line-length', '120']
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.282
    hooks:
    -   id: ruff
        args: ["--fix", "--line-length", "120"]
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        name: isort (python)
# doesn't use python interpreter in the terminal, so usually breaks
# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: 'v1.4.1'
#     hooks:
#     -   id: mypy
#         args: ["--install-types", "--ignore-missing-imports"]
